on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sshfs
        run: |
          sudo apt install sshfs
      - name: Install pnpm
        run: |
          sudo apt install nodejs npm
          sudo npm install -g pnpm
      - name: Install project dependencies
        run: |
          pnpm install
      - name: Write ssh keys and certs from secrets
        env:
          SSH_SKEY: ${{ secrets.SSH_SKEY_BASE64 }}
          SSH_PKEY: ${{ secrets.SSH_PKEY_BASE64 }}
          SSH_CERT: ${{ secrets.SSH_CERT_BASE64 }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG_BASE64 }}
        run: |
          mkdir -p ${HOME}/.ssh
          echo "$SSH_SKEY" | base64 --decode > ${HOME}/.ssh/id_eirb
          echo "$SSH_PKEY" | base64 --decode > ${HOME}/.ssh/id_eirb.pub
          echo "$SSH_CERT" | base64 --decode > ${HOME}/.ssh/id_eirb-cert.pub
          echo "$SSH_CONFIG" | base64 --decode > ${HOME}/.ssh/config
          chmod 400 ${HOME}/.ssh/*
      - name: Build eirb.fr
        run: |
          pnpm build
      - name: Mount server files
        run: |
          mkdir -p ${HOME}/mnt
          sshfs -o IdentityFile=${HOME}/.ssh/id_eirb -o StrictHostKeyChecking=no eirb: ${HOME}/mnt
      - name: Copy new version
        run: |
          cp -r dist/* ${HOME}/mnt/nginx/www
          umount ${HOME}/mnt
